# Site settings
name: Less Or More
email: xiaoyaoyiyiyun@163.com
author:  Blade
url: http://www.1love0.com
resume_site: http://www.1love0.com
github: https://github.com/LoveCodingLife
baseurl: ""
description: desc test hello
meta_description: desc test
motto: 1 lolve 0
banner: hell wolrd

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: LoveCodingLife
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light